# Generated by Django 5.2.14 on 2026-05-17 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image_base64', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=180)),
                ('image_base64', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('layout_type', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=260)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('time_label', models.CharField(blank=True, max_length=64)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=32, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True)),
                ('product_image_base64', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('procesando', 'Procesando')], default='procesando', max_length=16)),
                ('date_label', models.CharField(blank=True, max_length=64)),
                ('extra_info', models.TextField(blank=True)),
                ('can_download_invoice', models.BooleanField(default=False)),
                ('can_track', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('product_type', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('specs', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('stock_bajo', 'Stock bajo'), ('agotado', 'Agotado')], default='disponible', max_length=16)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('image_base64', models.TextField(blank=True)),
                ('is_offer', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
        ),
    ]
