# Generated by Django 5.2.15 on 2026-06-11 08:17

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_payment_syncstatus_rechazado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('procesando', 'Procesando'), ('rechazado', 'Rechazado')], default='procesando', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('bank_transfer', 'Transferencia Bancaria'), ('yape_plin', 'Yape / Plin')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sync_status',
            field=models.CharField(choices=[('en_espera', 'En espera'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='en_espera', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
