from django.urls import path

from .views import (
    CartAddView,
    CartClearView,
    CartItemDeleteView,
    CartItemUpdateView,
    CartView,
    CategoryListView,
    CheckoutView,
    EmployeeProductListCreateView,
    EmployeeSalesView,
    EmployeeDashboardView,
    EmployeeClientListView,
    EmployeeClientDeleteView,
    EmployeeDeliveryDetailView,
    EmployeeDeliveryListView,
    EmployeeDeliveryStaffListView,
    EmployeePaymentApproveView,
    EmployeePaymentDetailView,
    EmployeePaymentRejectView,
    EmployeePaymentsView,
    EmployeePendingPaymentsExcelView,
    MeView,
    NotificationListView,
    OrderListView,
    PaymentCreateView,
    PaymentDetailView,
    ProductDetailView,
    ProductListView,
    RegisterView,
)
from .views import AdminProtocolDashboardView, AdminOptimizeStockView

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('employee/dashboard/', EmployeeDashboardView.as_view(), name='employee_dashboard'),
    path('employee/admin-dashboard/', AdminProtocolDashboardView.as_view(), name='admin_protocol_dashboard'),
    path('employee/admin-dashboard/optimize-stock/', AdminOptimizeStockView.as_view(), name='admin_optimize_stock'),
    path('employee/sales/', EmployeeSalesView.as_view(), name='employee_sales'),
    path('employee/payments/', EmployeePaymentsView.as_view(), name='employee_payments'),
    path('employee/payments/export/', EmployeePendingPaymentsExcelView.as_view(), name='employee_payments_export'),
    path('employee/payments/<str:payment_code>/', EmployeePaymentDetailView.as_view(), name='employee_payment_detail'),
    path('employee/payments/<str:payment_code>/approve/', EmployeePaymentApproveView.as_view(), name='employee_payment_approve'),
    path('employee/payments/<str:payment_code>/reject/', EmployeePaymentRejectView.as_view(), name='employee_payment_reject'),
    path('employee/deliveries/', EmployeeDeliveryListView.as_view(), name='employee_deliveries'),
    path('employee/deliveries/<int:pk>/', EmployeeDeliveryDetailView.as_view(), name='employee_deliveries_detail'),
    path('employee/delivery-staff/', EmployeeDeliveryStaffListView.as_view(), name='employee_delivery_staff'),
    path('employee/clients/', EmployeeClientListView.as_view(), name='employee_clients'),
    path('employee/clients/<int:pk>/', EmployeeClientDeleteView.as_view(), name='employee_clients_delete'),
    path('employee/products/', EmployeeProductListCreateView.as_view(), name='employee_products'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/', CartAddView.as_view(), name='cart_add'),
    path('cart/items/<int:pk>/', CartItemDeleteView.as_view(), name='cart_item_delete'),
    path('cart/items/<int:pk>/update/', CartItemUpdateView.as_view(), name='cart_item_update'),
    path('cart/clear/', CartClearView.as_view(), name='cart_clear'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payments/', PaymentCreateView.as_view(), name='payments_create'),
    path('payments/<str:payment_code>/', PaymentDetailView.as_view(), name='payments_detail'),
    path('auth/register/', RegisterView.as_view(), name='auth_register'),
    path('auth/me/', MeView.as_view(), name='auth_me'),
]
